/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Event } from "@stencil/core";
import { LabeledDescriptorsArray } from "./components/input-face-api-webcam/TrainedModel";
import { CameraDirection } from "./utils/camera.service";
import { FaceDetectionError, iFaceDetected } from "./components/input-face-api-webcam/input-face-api-webcam";
import { DetectionImg } from "./utils/facepi.service";
import { FaceLandmarkerResult } from "@mediapipe/tasks-vision";
import { WebcamError } from "./components/input-file-from-webcam/input-file-from-webcam";
import { InputScanData } from "./components/input-scan-reader/input-scan-reader.types";
export { Event } from "@stencil/core";
export { LabeledDescriptorsArray } from "./components/input-face-api-webcam/TrainedModel";
export { CameraDirection } from "./utils/camera.service";
export { FaceDetectionError, iFaceDetected } from "./components/input-face-api-webcam/input-face-api-webcam";
export { DetectionImg } from "./utils/facepi.service";
export { FaceLandmarkerResult } from "@mediapipe/tasks-vision";
export { WebcamError } from "./components/input-file-from-webcam/input-file-from-webcam";
export { InputScanData } from "./components/input-scan-reader/input-scan-reader.types";
export namespace Components {
    /**
     * Camera-based barcode scanner component optimized for real-time scanning
     * with intelligent duplicate prevention and error recovery
     * Functions as a form input element with standard input properties
     */
    interface InputBarcode {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the scanner when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start scanning when component loads
         */
        "autoStart": boolean;
        /**
          * Camera configuration for optimal performance 10 FPS provides good balance between performance and accuracy
         */
        "cameraConfig": any;
        /**
          * Specific camera device ID to use (optional)
         */
        "cameraId"?: string;
        /**
          * Check validity of current value
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Camera facing mode: 'user' for front camera, 'environment' for back camera
         */
        "facingMode": 'user' | 'environment';
        /**
          * Get available cameras for the device
          * @returns Promise resolving to array of camera devices
         */
        "getCameras": () => Promise<any[]>;
        /**
          * Get form value for form submission
         */
        "getFormValue": () => Promise<string>;
        /**
          * Get current scanner state
         */
        "getState": () => Promise<any | null>;
        /**
          * Height of the camera viewport
         */
        "height": string;
        /**
          * Maximum length for scanned value
         */
        "maxlength"?: number;
        /**
          * Minimum length for scanned value
         */
        "minlength"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Pattern for input validation (regex)
         */
        "pattern"?: string;
        /**
          * Placeholder text when no value is present
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Blur the scanner (stop scanning)
         */
        "setBlur": () => Promise<void>;
        /**
          * Focus the scanner (start scanning)
         */
        "setFocus": () => Promise<void>;
        /**
          * Set form value programmatically
         */
        "setFormValue": (value: string) => Promise<void>;
        /**
          * Start the barcode scanner
         */
        "start": () => Promise<void>;
        /**
          * Stop the scanner and clean up resources
         */
        "stop": () => Promise<void>;
        /**
          * Supported barcode and QR code formats for scanning Optimized selection for best performance Using format constants compatible with html5-qrcode v2.3.8+
         */
        "supportedFormats": number[];
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (last scanned data)
         */
        "value"?: string;
        /**
          * Width of the camera viewport
         */
        "width": string;
    }
    /**
     * AI-powered face detection and recognition component
     * High-performance facial analysis with MediaPipe and TensorFlow.js
     * Optimized for real-time detection with Web Workers
     * Functions as a form input element for facial recognition data
     */
    interface InputFaceApiWebcam {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Enable automatic photo capture when face is detected
         */
        "autoCapture": boolean;
        /**
          * Auto-focus the detection when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start detection when component loads
         */
        "autoStart": boolean;
        /**
          * Delay between automatic photo captures in milliseconds
         */
        "captureDelay": number;
        /**
          * Minimum confidence score for face detection to trigger photo capture
         */
        "captureThreshold": number;
        /**
          * Check validity of the input
         */
        "checkValidity": () => Promise<boolean>;
        "customValidation"?: (value: string) => boolean;
        /**
          * Manually trigger a single face detection
          * @returns Promise with detection result including landmarks
         */
        "detectFaceManually": () => Promise<iFaceDetected | null>;
        /**
          * Detection mode: 'interval' for automatic detection every X ms, 'manual' for on-demand detection
         */
        "detectionMode": 'interval' | 'manual';
        /**
          * Detection timer interval in milliseconds
         */
        "detectionTimer"?: number;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Enable or disable face detection
         */
        "enableDetection": boolean;
        /**
          * Facing mode options following https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode#value
         */
        "facingMode"?: CameraDirection;
        /**
          * Text for the flip camera button
         */
        "flipButtonText": string;
        /**
          * Giving a blob image, get the face landmarks
          * @returns face landmarks
         */
        "getBlobImageDescriptors": (blob: Blob) => Promise<FaceLandmarkerResult>;
        /**
          * Get current face confidence score
          * @returns Confidence score (0-1) or null if no face detected
         */
        "getCurrentConfidence": () => Promise<number | null>;
        /**
          * Get current face landmarks if a face is detected
          * @returns Array of landmark points or null if no face detected
         */
        "getCurrentLandmarks": () => Promise<any[] | null>;
        /**
          * Diagnostic method to check detection status
         */
        "getDiagnosticInfo": () => Promise<any>;
        /**
          * Giving current face in video canvas, get the face landmarks
          * @returns face landmarks
         */
        "getFaceLandMarks": () => Promise<FaceLandmarkerResult>;
        /**
          * Get the current form value
         */
        "getFormValue": () => Promise<string>;
        /**
          * Get validation message
         */
        "getValidationMessage": () => Promise<string>;
        /**
          * Height of the video element
         */
        "height"?: number;
        /**
          * Initialize camera and face detection
         */
        "initializeCamera": () => Promise<void>;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Placeholder text when no face is detected
         */
        "placeholder"?: string;
        /**
          * Predicts best face match, uses worker to calculate distance between the given blob and the trained model passed in trainedModel prop
          * @param blob
          * @returns
         */
        "predictBestMatch": (blob?: Blob) => Promise<any>;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Score threshold to detect a face
         */
        "scoreThreshold"?: number;
        /**
          * Blur the component (stop camera and detection)
         */
        "setBlur": () => Promise<void>;
        /**
          * Set custom validity
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Set detection mode programmatically
          * @param mode 'interval' for automatic detection, 'manual' for on-demand
         */
        "setDetectionMode": (mode: "interval" | "manual") => Promise<void>;
        /**
          * Focus the component (start camera and detection)
         */
        "setFocus": () => Promise<void>;
        /**
          * Set the form value
         */
        "setFormValue": (value: string) => Promise<void>;
        /**
          * Show bounding boxes around detected faces
         */
        "showBoundingBoxes": boolean;
        /**
          * Show control buttons for starting/stopping detection
         */
        "showControls": boolean;
        /**
          * Show face landmarks on detected faces
         */
        "showLandmarks": boolean;
        /**
          * Text for the start detection button
         */
        "startButtonText": string;
        /**
          * Start face detection
         */
        "startDetection": () => Promise<void>;
        /**
          * Text for the stop detection button
         */
        "stopButtonText": string;
        /**
          * Stop face detection
         */
        "stopDetection": () => Promise<void>;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Toggle camera between front and back
         */
        "toggleCamera": () => Promise<void>;
        /**
          * Trained models to use for recognition and best match
         */
        "trainedModel"?: LabeledDescriptorsArray;
        /**
          * Use optimized Web Worker for face detection (recommended for better performance)
         */
        "useOptimizedDetection": boolean;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (JSON string of face detection data)
         */
        "value"?: string;
        /**
          * Width of the video element
         */
        "width"?: number;
    }
    /**
     * Simple webcam photo capture component optimized for performance
     * Perfect for employee check-ins, ID verification, and quick photo capture
     * Functions as a form input element for file/image submission
     */
    interface InputFileFromWebcam {
        /**
          * Accept attribute for file type validation
         */
        "accept"?: string;
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the camera when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start camera when component loads
         */
        "autoStart"?: boolean;
        /**
          * Text for the capture button
         */
        "captureButtonText"?: string;
        /**
          * Check validity of current value
         */
        "checkValidity": () => Promise<boolean>;
        "customValidation"?: (value: string) => boolean;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Custom canvas drawing function for image processing Override to add filters or effects to captured images
         */
        "drawImageCb"?: Function;
        /**
          * Camera facing mode: front or back camera
         */
        "facingMode"?: CameraDirection;
        /**
          * Enable flash effect animation when taking picture
         */
        "flashEffect"?: boolean;
        /**
          * Text for the flip camera button
         */
        "flipButtonText"?: string;
        /**
          * Get form value for form submission (base64 data URL)
         */
        "getFormValue": () => Promise<string>;
        /**
          * Height of the video element in pixels
         */
        "height"?: number;
        /**
          * Image quality for captured photos (0.1 to 1.0)
         */
        "imageQuality"?: number;
        /**
          * Maximum file size in bytes (0 = no limit)
         */
        "maxFileSize"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Placeholder text when no image is captured
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Force release camera (useful when component is hidden in modal)
         */
        "releaseCamera": () => Promise<void>;
        /**
          * Request camera access (useful when component becomes visible from modal)
         */
        "requestCamera": () => Promise<void>;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Reset camera by stopping and restarting
         */
        "resetCamera": () => Promise<void>;
        /**
          * Blur the camera (stop camera)
         */
        "setBlur": () => Promise<void>;
        /**
          * Focus the camera (start camera)
         */
        "setFocus": () => Promise<void>;
        /**
          * Set form value programmatically
         */
        "setFormValue": (value: string) => Promise<void>;
        /**
          * Show action buttons (capture and flip camera buttons)
         */
        "showActionButtons"?: boolean;
        /**
          * Show camera control buttons (flip, capture, etc.)
         */
        "showControls"?: boolean;
        /**
          * Start the camera with error handling
         */
        "startCamera": () => Promise<void>;
        /**
          * Stop the camera and clean up resources
         */
        "stopCamera": () => Promise<void>;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Take a picture with flash effect and error handling
         */
        "takePic": () => Promise<Blob>;
        /**
          * Toggle between front and back camera
         */
        "toggleCamera": () => Promise<void>;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (base64 data URL of captured image)
         */
        "value"?: string;
        /**
          * Width of the video element in pixels
         */
        "width"?: number;
    }
    /**
     * Hardware barcode scanner input component
     * Optimized for physical barcode scanners that input as HID keyboard devices
     * Handles rapid input patterns with intelligent timeout management
     * Functions as a form input element with standard input properties
     */
    interface InputScanReader {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the scanner when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Check validity of current value
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Get processed scan data
         */
        "getData": () => Promise<InputScanData | null>;
        /**
          * Get form value for form submission
         */
        "getFormValue": () => Promise<string>;
        /**
          * Get current raw scanned text
         */
        "getText": () => Promise<string>;
        /**
          * Timeout duration in milliseconds before clearing incomplete input
         */
        "inputTimeout"?: number;
        /**
          * Maximum length for scanned value
         */
        "maxlength"?: number;
        /**
          * Minimum input length to consider valid scanner input
         */
        "minInputLength"?: number;
        /**
          * Minimum length for scanned value
         */
        "minlength"?: number;
        /**
          * Duration in milliseconds to show confirmation modal after successful scan
         */
        "modalTimer"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Pattern for input validation (regex)
         */
        "pattern"?: string;
        /**
          * Placeholder text when no value is present
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Title text displayed during scanning operation
         */
        "scanTitle"?: string;
        /**
          * Blur the scanner (stop scanning)
         */
        "setBlur": () => Promise<void>;
        /**
          * Focus the scanner (start scanning)
         */
        "setFocus": () => Promise<void>;
        /**
          * Set form value programmatically
         */
        "setFormValue": (value: string) => Promise<void>;
        /**
          * Start scanning mode
         */
        "start": () => Promise<void>;
        /**
          * Stop scanning mode
         */
        "stop": () => Promise<void>;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (last scanned data)
         */
        "value"?: string;
    }
}
export interface InputBarcodeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputBarcodeElement;
}
export interface InputFaceApiWebcamCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputFaceApiWebcamElement;
}
export interface InputFileFromWebcamCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputFileFromWebcamElement;
}
export interface InputScanReaderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLInputScanReaderElement;
}
declare global {
    interface HTMLInputBarcodeElementEventMap {
        "inputChange": Event;
        "valueChange": Event;
        "focusGained": FocusEvent;
        "focusLost": FocusEvent;
        "validationFailed": Event;
        "scan": string;
    }
    /**
     * Camera-based barcode scanner component optimized for real-time scanning
     * with intelligent duplicate prevention and error recovery
     * Functions as a form input element with standard input properties
     */
    interface HTMLInputBarcodeElement extends Components.InputBarcode, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInputBarcodeElementEventMap>(type: K, listener: (this: HTMLInputBarcodeElement, ev: InputBarcodeCustomEvent<HTMLInputBarcodeElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInputBarcodeElementEventMap>(type: K, listener: (this: HTMLInputBarcodeElement, ev: InputBarcodeCustomEvent<HTMLInputBarcodeElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInputBarcodeElement: {
        prototype: HTMLInputBarcodeElement;
        new (): HTMLInputBarcodeElement;
    };
    interface HTMLInputFaceApiWebcamElementEventMap {
        "faceDetected": iFaceDetected;
        "faceStopDetection": void;
        "detectionStarted": void;
        "detectionStopped": void;
        "cameraStarted": MediaStream;
        "cameraStopped": void;
        "cameraError": FaceDetectionError;
        "facingModeChanged": CameraDirection;
        "photoCapture": Blob;
        "inputChange": Event;
        "valueChange": Event;
        "focusGained": FocusEvent;
        "focusLost": FocusEvent;
        "validationFailed": Event;
    }
    /**
     * AI-powered face detection and recognition component
     * High-performance facial analysis with MediaPipe and TensorFlow.js
     * Optimized for real-time detection with Web Workers
     * Functions as a form input element for facial recognition data
     */
    interface HTMLInputFaceApiWebcamElement extends Components.InputFaceApiWebcam, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInputFaceApiWebcamElementEventMap>(type: K, listener: (this: HTMLInputFaceApiWebcamElement, ev: InputFaceApiWebcamCustomEvent<HTMLInputFaceApiWebcamElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInputFaceApiWebcamElementEventMap>(type: K, listener: (this: HTMLInputFaceApiWebcamElement, ev: InputFaceApiWebcamCustomEvent<HTMLInputFaceApiWebcamElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInputFaceApiWebcamElement: {
        prototype: HTMLInputFaceApiWebcamElement;
        new (): HTMLInputFaceApiWebcamElement;
    };
    interface HTMLInputFileFromWebcamElementEventMap {
        "pictureTaken": Blob;
        "inputChange": Event;
        "valueChange": Event;
        "focusGained": FocusEvent;
        "focusLost": FocusEvent;
        "validationFailed": Event;
        "facingModeChanged": CameraDirection;
        "cameraStarted": void;
        "cameraStopped": void;
        "cameraError": WebcamError;
    }
    /**
     * Simple webcam photo capture component optimized for performance
     * Perfect for employee check-ins, ID verification, and quick photo capture
     * Functions as a form input element for file/image submission
     */
    interface HTMLInputFileFromWebcamElement extends Components.InputFileFromWebcam, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInputFileFromWebcamElementEventMap>(type: K, listener: (this: HTMLInputFileFromWebcamElement, ev: InputFileFromWebcamCustomEvent<HTMLInputFileFromWebcamElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInputFileFromWebcamElementEventMap>(type: K, listener: (this: HTMLInputFileFromWebcamElement, ev: InputFileFromWebcamCustomEvent<HTMLInputFileFromWebcamElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInputFileFromWebcamElement: {
        prototype: HTMLInputFileFromWebcamElement;
        new (): HTMLInputFileFromWebcamElement;
    };
    interface HTMLInputScanReaderElementEventMap {
        "scan": InputScanData;
        "inputChange": Event;
        "valueChange": Event;
        "focusGained": FocusEvent;
        "focusLost": FocusEvent;
        "validationFailed": Event;
    }
    /**
     * Hardware barcode scanner input component
     * Optimized for physical barcode scanners that input as HID keyboard devices
     * Handles rapid input patterns with intelligent timeout management
     * Functions as a form input element with standard input properties
     */
    interface HTMLInputScanReaderElement extends Components.InputScanReader, HTMLStencilElement {
        addEventListener<K extends keyof HTMLInputScanReaderElementEventMap>(type: K, listener: (this: HTMLInputScanReaderElement, ev: InputScanReaderCustomEvent<HTMLInputScanReaderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLInputScanReaderElementEventMap>(type: K, listener: (this: HTMLInputScanReaderElement, ev: InputScanReaderCustomEvent<HTMLInputScanReaderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLInputScanReaderElement: {
        prototype: HTMLInputScanReaderElement;
        new (): HTMLInputScanReaderElement;
    };
    interface HTMLElementTagNameMap {
        "input-barcode": HTMLInputBarcodeElement;
        "input-face-api-webcam": HTMLInputFaceApiWebcamElement;
        "input-file-from-webcam": HTMLInputFileFromWebcamElement;
        "input-scan-reader": HTMLInputScanReaderElement;
    }
}
declare namespace LocalJSX {
    /**
     * Camera-based barcode scanner component optimized for real-time scanning
     * with intelligent duplicate prevention and error recovery
     * Functions as a form input element with standard input properties
     */
    interface InputBarcode {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the scanner when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start scanning when component loads
         */
        "autoStart"?: boolean;
        /**
          * Camera configuration for optimal performance 10 FPS provides good balance between performance and accuracy
         */
        "cameraConfig"?: any;
        /**
          * Specific camera device ID to use (optional)
         */
        "cameraId"?: string;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Camera facing mode: 'user' for front camera, 'environment' for back camera
         */
        "facingMode"?: 'user' | 'environment';
        /**
          * Height of the camera viewport
         */
        "height"?: string;
        /**
          * Maximum length for scanned value
         */
        "maxlength"?: number;
        /**
          * Minimum length for scanned value
         */
        "minlength"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Emitted when component gains focus (standard form event)
         */
        "onFocusGained"?: (event: InputBarcodeCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when component loses focus (standard form event)
         */
        "onFocusLost"?: (event: InputBarcodeCustomEvent<FocusEvent>) => void;
        /**
          * Emitted when input value changes (standard form event)
         */
        "onInputChange"?: (event: InputBarcodeCustomEvent<Event>) => void;
        /**
          * Emitted when a barcode is successfully scanned
         */
        "onScan"?: (event: InputBarcodeCustomEvent<string>) => void;
        /**
          * Emitted when input validation fails (standard form event)
         */
        "onValidationFailed"?: (event: InputBarcodeCustomEvent<Event>) => void;
        /**
          * Emitted when input value is committed (standard form event)
         */
        "onValueChange"?: (event: InputBarcodeCustomEvent<Event>) => void;
        /**
          * Pattern for input validation (regex)
         */
        "pattern"?: string;
        /**
          * Placeholder text when no value is present
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Supported barcode and QR code formats for scanning Optimized selection for best performance Using format constants compatible with html5-qrcode v2.3.8+
         */
        "supportedFormats"?: number[];
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (last scanned data)
         */
        "value"?: string;
        /**
          * Width of the camera viewport
         */
        "width"?: string;
    }
    /**
     * AI-powered face detection and recognition component
     * High-performance facial analysis with MediaPipe and TensorFlow.js
     * Optimized for real-time detection with Web Workers
     * Functions as a form input element for facial recognition data
     */
    interface InputFaceApiWebcam {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Enable automatic photo capture when face is detected
         */
        "autoCapture"?: boolean;
        /**
          * Auto-focus the detection when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start detection when component loads
         */
        "autoStart"?: boolean;
        /**
          * Delay between automatic photo captures in milliseconds
         */
        "captureDelay"?: number;
        /**
          * Minimum confidence score for face detection to trigger photo capture
         */
        "captureThreshold"?: number;
        "customValidation"?: (value: string) => boolean;
        /**
          * Detection mode: 'interval' for automatic detection every X ms, 'manual' for on-demand detection
         */
        "detectionMode"?: 'interval' | 'manual';
        /**
          * Detection timer interval in milliseconds
         */
        "detectionTimer"?: number;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Enable or disable face detection
         */
        "enableDetection"?: boolean;
        /**
          * Facing mode options following https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/facingMode#value
         */
        "facingMode"?: CameraDirection;
        /**
          * Text for the flip camera button
         */
        "flipButtonText"?: string;
        /**
          * Height of the video element
         */
        "height"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Event emitted when camera encounters an error
         */
        "onCameraError"?: (event: InputFaceApiWebcamCustomEvent<FaceDetectionError>) => void;
        /**
          * Event emitted when camera starts successfully
         */
        "onCameraStarted"?: (event: InputFaceApiWebcamCustomEvent<MediaStream>) => void;
        /**
          * Event emitted when camera stops
         */
        "onCameraStopped"?: (event: InputFaceApiWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when detection starts
         */
        "onDetectionStarted"?: (event: InputFaceApiWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when detection stops
         */
        "onDetectionStopped"?: (event: InputFaceApiWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when a face is detected in video stream
         */
        "onFaceDetected"?: (event: InputFaceApiWebcamCustomEvent<iFaceDetected>) => void;
        /**
          * Event emitted when face detection was stopped
         */
        "onFaceStopDetection"?: (event: InputFaceApiWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when facing mode changes
         */
        "onFacingModeChanged"?: (event: InputFaceApiWebcamCustomEvent<CameraDirection>) => void;
        /**
          * Standard focus event
         */
        "onFocusGained"?: (event: InputFaceApiWebcamCustomEvent<FocusEvent>) => void;
        /**
          * Standard blur event
         */
        "onFocusLost"?: (event: InputFaceApiWebcamCustomEvent<FocusEvent>) => void;
        /**
          * Standard input event when face detection data changes
         */
        "onInputChange"?: (event: InputFaceApiWebcamCustomEvent<Event>) => void;
        /**
          * Event emitted when a photo is automatically captured
         */
        "onPhotoCapture"?: (event: InputFaceApiWebcamCustomEvent<Blob>) => void;
        /**
          * Standard invalid event for form validation
         */
        "onValidationFailed"?: (event: InputFaceApiWebcamCustomEvent<Event>) => void;
        /**
          * Standard change event when detection data is committed
         */
        "onValueChange"?: (event: InputFaceApiWebcamCustomEvent<Event>) => void;
        /**
          * Placeholder text when no face is detected
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Score threshold to detect a face
         */
        "scoreThreshold"?: number;
        /**
          * Show bounding boxes around detected faces
         */
        "showBoundingBoxes"?: boolean;
        /**
          * Show control buttons for starting/stopping detection
         */
        "showControls"?: boolean;
        /**
          * Show face landmarks on detected faces
         */
        "showLandmarks"?: boolean;
        /**
          * Text for the start detection button
         */
        "startButtonText"?: string;
        /**
          * Text for the stop detection button
         */
        "stopButtonText"?: string;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Trained models to use for recognition and best match
         */
        "trainedModel"?: LabeledDescriptorsArray;
        /**
          * Use optimized Web Worker for face detection (recommended for better performance)
         */
        "useOptimizedDetection"?: boolean;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (JSON string of face detection data)
         */
        "value"?: string;
        /**
          * Width of the video element
         */
        "width"?: number;
    }
    /**
     * Simple webcam photo capture component optimized for performance
     * Perfect for employee check-ins, ID verification, and quick photo capture
     * Functions as a form input element for file/image submission
     */
    interface InputFileFromWebcam {
        /**
          * Accept attribute for file type validation
         */
        "accept"?: string;
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the camera when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Auto-start camera when component loads
         */
        "autoStart"?: boolean;
        /**
          * Text for the capture button
         */
        "captureButtonText"?: string;
        "customValidation"?: (value: string) => boolean;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Custom canvas drawing function for image processing Override to add filters or effects to captured images
         */
        "drawImageCb"?: Function;
        /**
          * Camera facing mode: front or back camera
         */
        "facingMode"?: CameraDirection;
        /**
          * Enable flash effect animation when taking picture
         */
        "flashEffect"?: boolean;
        /**
          * Text for the flip camera button
         */
        "flipButtonText"?: string;
        /**
          * Height of the video element in pixels
         */
        "height"?: number;
        /**
          * Image quality for captured photos (0.1 to 1.0)
         */
        "imageQuality"?: number;
        /**
          * Maximum file size in bytes (0 = no limit)
         */
        "maxFileSize"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Event emitted when camera encounters an error
         */
        "onCameraError"?: (event: InputFileFromWebcamCustomEvent<WebcamError>) => void;
        /**
          * Event emitted when camera starts successfully
         */
        "onCameraStarted"?: (event: InputFileFromWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when camera stops
         */
        "onCameraStopped"?: (event: InputFileFromWebcamCustomEvent<void>) => void;
        /**
          * Event emitted when facing mode changes
         */
        "onFacingModeChanged"?: (event: InputFileFromWebcamCustomEvent<CameraDirection>) => void;
        /**
          * Standard focus event
         */
        "onFocusGained"?: (event: InputFileFromWebcamCustomEvent<FocusEvent>) => void;
        /**
          * Standard blur event
         */
        "onFocusLost"?: (event: InputFileFromWebcamCustomEvent<FocusEvent>) => void;
        /**
          * Standard input event when value changes
         */
        "onInputChange"?: (event: InputFileFromWebcamCustomEvent<Event>) => void;
        /**
          * Event emitted when the user takes a picture
         */
        "onPictureTaken"?: (event: InputFileFromWebcamCustomEvent<Blob>) => void;
        /**
          * Standard invalid event for form validation
         */
        "onValidationFailed"?: (event: InputFileFromWebcamCustomEvent<Event>) => void;
        /**
          * Standard change event when value is committed
         */
        "onValueChange"?: (event: InputFileFromWebcamCustomEvent<Event>) => void;
        /**
          * Placeholder text when no image is captured
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Show action buttons (capture and flip camera buttons)
         */
        "showActionButtons"?: boolean;
        /**
          * Show camera control buttons (flip, capture, etc.)
         */
        "showControls"?: boolean;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (base64 data URL of captured image)
         */
        "value"?: string;
        /**
          * Width of the video element in pixels
         */
        "width"?: number;
    }
    /**
     * Hardware barcode scanner input component
     * Optimized for physical barcode scanners that input as HID keyboard devices
     * Handles rapid input patterns with intelligent timeout management
     * Functions as a form input element with standard input properties
     */
    interface InputScanReader {
        /**
          * ARIA label for accessibility
         */
        "accessibilityLabel"?: string;
        /**
          * ARIA description for accessibility
         */
        "ariaDescribedby"?: string;
        /**
          * Auto-focus the scanner when component loads
         */
        "autoFocus"?: boolean;
        /**
          * Whether the input is disabled
         */
        "disabled"?: boolean;
        /**
          * Timeout duration in milliseconds before clearing incomplete input
         */
        "inputTimeout"?: number;
        /**
          * Maximum length for scanned value
         */
        "maxlength"?: number;
        /**
          * Minimum input length to consider valid scanner input
         */
        "minInputLength"?: number;
        /**
          * Minimum length for scanned value
         */
        "minlength"?: number;
        /**
          * Duration in milliseconds to show confirmation modal after successful scan
         */
        "modalTimer"?: number;
        /**
          * The name attribute for form submission
         */
        "name"?: string;
        /**
          * Standard focus event
         */
        "onFocusGained"?: (event: InputScanReaderCustomEvent<FocusEvent>) => void;
        /**
          * Standard blur event
         */
        "onFocusLost"?: (event: InputScanReaderCustomEvent<FocusEvent>) => void;
        /**
          * Standard input event when value changes
         */
        "onInputChange"?: (event: InputScanReaderCustomEvent<Event>) => void;
        /**
          * Event emitted when scanner completes reading
         */
        "onScan"?: (event: InputScanReaderCustomEvent<InputScanData>) => void;
        /**
          * Standard invalid event for form validation
         */
        "onValidationFailed"?: (event: InputScanReaderCustomEvent<Event>) => void;
        /**
          * Standard change event when value is committed
         */
        "onValueChange"?: (event: InputScanReaderCustomEvent<Event>) => void;
        /**
          * Pattern for input validation (regex)
         */
        "pattern"?: string;
        /**
          * Placeholder text when no value is present
         */
        "placeholder"?: string;
        /**
          * Whether the input is readonly
         */
        "readonly"?: boolean;
        /**
          * Whether the input is required for form validation
         */
        "required"?: boolean;
        /**
          * Title text displayed during scanning operation
         */
        "scanTitle"?: string;
        /**
          * Tab order for keyboard navigation
         */
        "tabOrder"?: number;
        /**
          * Form validation message
         */
        "validationMessage"?: string;
        /**
          * The value of the input (last scanned data)
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "input-barcode": InputBarcode;
        "input-face-api-webcam": InputFaceApiWebcam;
        "input-file-from-webcam": InputFileFromWebcam;
        "input-scan-reader": InputScanReader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Camera-based barcode scanner component optimized for real-time scanning
             * with intelligent duplicate prevention and error recovery
             * Functions as a form input element with standard input properties
             */
            "input-barcode": LocalJSX.InputBarcode & JSXBase.HTMLAttributes<HTMLInputBarcodeElement>;
            /**
             * AI-powered face detection and recognition component
             * High-performance facial analysis with MediaPipe and TensorFlow.js
             * Optimized for real-time detection with Web Workers
             * Functions as a form input element for facial recognition data
             */
            "input-face-api-webcam": LocalJSX.InputFaceApiWebcam & JSXBase.HTMLAttributes<HTMLInputFaceApiWebcamElement>;
            /**
             * Simple webcam photo capture component optimized for performance
             * Perfect for employee check-ins, ID verification, and quick photo capture
             * Functions as a form input element for file/image submission
             */
            "input-file-from-webcam": LocalJSX.InputFileFromWebcam & JSXBase.HTMLAttributes<HTMLInputFileFromWebcamElement>;
            /**
             * Hardware barcode scanner input component
             * Optimized for physical barcode scanners that input as HID keyboard devices
             * Handles rapid input patterns with intelligent timeout management
             * Functions as a form input element with standard input properties
             */
            "input-scan-reader": LocalJSX.InputScanReader & JSXBase.HTMLAttributes<HTMLInputScanReaderElement>;
        }
    }
}
